/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import Estadistica.src.estadistica.Grafico;
import control.tiempo.usuario.ControlIngreso;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import manejoProductos.categoria.Categoria;
import manejoProductos.categoria.CategoriaServicioFabrica;
import manejoProductos.categoria.ICategoriaServicio;
import manejoProductos.transaccion.IServicioTransaccion;
import manejoProductos.transaccion.ServicioTransaccionFabrica;
import manejoProductos.transaccion.Transaccion;
import manejoProductos.validador.Validador;

/**
 *
 * @author Brayan
 */
public class Principal extends javax.swing.JFrame {

    VProducto rp = new VProducto();
    Tabla tb = new Tabla();
    VCategoria c = new VCategoria();
    VAlmacen a = new VAlmacen();
    TipoGuardado tg = new TipoGuardado();
    Entradas e = new Entradas();
    Salidas s = new Salidas();
    VProducto ts = new VProducto();
    VUsuario u = new VUsuario();
    Proveedor p = new Proveedor();
    InformeEntrada ie = new InformeEntrada();
    InformeSalidas is = new InformeSalidas();
    TablaExistencia te =new TablaExistencia();
    ControlIngreso control;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(1200, 800);
        this.setLocationRelativeTo(null);
        jMenuBar1.setSize(1200, 100);

        ocultarVentanas();
        this.add(te).setBounds(0, 0, 1200, 800);
        //ex.setVisible(true);
        te.setVisible(true);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/vistas/imagenes/cajas.png"));
        setIconImage(iconoPropio);
        control = new ControlIngreso();
        control.inicio(Validador.getUsuario().getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        RCProducto = new javax.swing.JMenuItem();
        MCProducto = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        MenuUsuario = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem9.setText("jMenuItem9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jButton1.setText("jButton1");

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 51));
        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/transaccion.png"))); // NOI18N
        jMenu1.setText("Registrar");

        jMenuItem1.setText("Registrar Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Modificar Producto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        RCProducto.setText("Registrar Categoria Producto");
        RCProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCProductoActionPerformed(evt);
            }
        });
        jMenu1.add(RCProducto);

        MCProducto.setText("Modificar Categoria Producto");
        MCProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MCProductoActionPerformed(evt);
            }
        });
        jMenu1.add(MCProducto);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Transacciones");

        jMenuItem4.setText("Entradas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem7.setText("Salidas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        MenuUsuario.setText("Usuarios");

        jMenuItem6.setText("Registrar Usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        MenuUsuario.add(jMenuItem6);

        jMenuItem13.setText("Modificar/Eliminar Usuario");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        MenuUsuario.add(jMenuItem13);

        jMenuItem8.setText("Login");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        MenuUsuario.add(jMenuItem8);

        jMenuBar1.add(MenuUsuario);

        jMenu5.setText("Consultas");

        jMenuItem5.setText("Existencia");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem11.setText("Salidas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Entradas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuBar1.add(jMenu5);

        jMenu7.setText("Almacenes");

        jMenuItem14.setText("Registrar Almacen");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem14);

        jMenuItem15.setText("Modificar Almacen");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenuBar1.add(jMenu7);

        jMenu6.setText("Estadisticas");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenu6KeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu2.setText("Salir");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ocultarVentanas();
        
        this.add(e).setBounds(0, 0, 1200, 800);
        e.setVisible(true);
        e.llenarTablaProductos();
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ocultarVentanas();
        this.add(s).setBounds(0, 0, 1200, 800);
        s.setVisible(true);
        s.llenarTablaProductos();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        ocultarVentanas();
        this.add(a).setBounds(0, 0, 1200, 800);
        a.setVisible(true);
        a.btnRegistrarAlmacen.setVisible(true);
        a.btnModificarAlmacen.setVisible(false);
        a.bandera = false;
        a.limpiarCampos();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        ocultarVentanas();
        this.add(a).setBounds(0, 0, 1200, 800);
        a.setVisible(true);
        a.btnRegistrarAlmacen.setVisible(false);
        a.btnModificarAlmacen.setVisible(true);
        a.bandera = true;
        a.limpiarCampos();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ocultarVentanas();
        this.add(u).setBounds(0, 0, 1200, 800);
        u.setVisible(true);
        u.banderaUsuario = false;
        u.btnRegistrar.setVisible(true);
        u.btnActualizar.setVisible(false);
        u.btnEliminar.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void RCProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCProductoActionPerformed

        ocultarVentanas();
        this.add(c).setBounds(0, 0, 1200, 800);
        c.setVisible(true);
        c.llenarTabla();
        c.btnModificar.setVisible(false);
        c.btnRegistrar.setVisible(true);
    }//GEN-LAST:event_RCProductoActionPerformed

    public void llenarTablaCategoria(ArrayList<Categoria> categoria) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("nombre");
        this.tb.jTable1.setModel(model);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        rp.bandera = false;
        ocultarVentanas();
        this.add(rp).setBounds(0, 0, 1200, 800);
        rp.setVisible(true);
        rp.jComboBox1.removeAllItems();

        rp.llenarComboBox();
        rp.llenarTablaProductos();
        rp.jLabel7.setText("Producto");
        rp.btnModificar.setVisible(false);
        rp.btnRegistrar.setVisible(true);
        rp.limpiarCampos();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ocultarVentanas();
        Login l = new Login();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ocultarVentanas();
        this.add(te).setBounds(0, 0, 1200, 800);
        te.setVisible(true);
        te.llenarTablaExistencia();
        //ex.setVisible(true);
        //ex.jLabel1.setText("Existencias");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ocultarVentanas();
        this.add(is).setBounds(0, 0, 1200, 800);
        is.setVisible(true);
        is.jLabel1.setText("Salidas");
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ocultarVentanas();
        this.add(ie).setBounds(0, 0, 1200, 800);
        ie.setVisible(true);
        ie.jLabel1.setText("Entradas");
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ocultarVentanas();
        this.add(rp).setBounds(0, 0, 1200, 800);
        rp.bandera = true;
        rp.setVisible(true);
        rp.llenarTablaProductos();
        rp.jLabel7.setText("Producto");
        rp.btnRegistrar.setVisible(false);
        rp.btnModificar.setVisible(true);
        rp.txtCod.setEditable(false);
        rp.limpiarCampos();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MCProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MCProductoActionPerformed
        ocultarVentanas();
        this.add(c).setBounds(0, 0, 1200, 800);
        c.setVisible(true);
        c.llenarTabla();
        c.btnModificar.setVisible(true);
        c.btnRegistrar.setVisible(false);
    }//GEN-LAST:event_MCProductoActionPerformed

    
    
    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        
        control.fin();
        
        System.exit( 0 );
        
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        ocultarVentanas();
        this.add(u).setBounds(0, 0, 1200, 800);
        u.setVisible(true);
        u.banderaUsuario = true;
        u.btnRegistrar.setVisible(false);
        u.btnActualizar.setVisible(true);
        u.btnEliminar.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        ocultarVentanas();
        Grafico g = new Grafico();
        IServicioTransaccion e = ServicioTransaccionFabrica.construir();
        var resultado = e.obtener("'Entrada'");
        System.out.println(resultado.size()+"este es su tamaño");
        for(Transaccion item : resultado){
            g.cargarCategoriaLista(item.getCantidad(), item.getProdcuto().getCategoria().getNombre());
            g.cargarDatos();
            g.actualizarGraficos();
        }
        g.setVisible(true);
        //this.hide();
        
        
        
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu6KeyPressed
        
    }//GEN-LAST:event_jMenu6KeyPressed

    private void ocultarVentanas() {
        rp.setVisible(false);
        tb.setVisible(false);
        c.setVisible(false);
        a.setVisible(false);
        e.setVisible(false);
        s.setVisible(false);
        p.setVisible(false);
        tg.setVisible(false);
        ts.setVisible(false);
        u.setVisible(false);
        is.setVisible(false);
        ie.setVisible(false);
        te.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MCProducto;
    private javax.swing.JMenu MenuUsuario;
    private javax.swing.JMenuItem RCProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
