/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import manejoProductos.categoria.Categoria;
import manejoProductos.existencia.Existencia;
import manejoProductos.existencia.IServicioExistencia;
import manejoProductos.existencia.ServicioExistenciaFabrica;
import manejoProductos.producto.IProductoServicio;
import manejoProductos.producto.Producto;
import manejoProductos.producto.ProductoServicioFabrica;

/**
 *
 * @author Brayan
 */
public class TablaExistencia extends javax.swing.JPanel {

    DefaultTableModel modelo;
    /**
     * Creates new form Tabla
     */
    public TablaExistencia() {
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Almacen");
        modelo.addColumn("tipo Almacen");
        modelo.addColumn("Codigo Producto");
        modelo.addColumn("nombre Producto");
        modelo.addColumn("Descripcion Producto");
        modelo.addColumn("Categoria");
        modelo.addColumn("PCompra");
        modelo.addColumn("PVenta");
        modelo.addColumn("modoGuardado");
        modelo.addColumn("ubicacion dentro el almacen");
        modelo.addColumn("cantidad");
        this.jTable1.setModel(modelo);
        
        llenarTablaExistencia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setPreferredSize(new java.awt.Dimension(1200, 800));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(255, 204, 102));
        jButton2.setText("Buscar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout tablaLayout = new javax.swing.GroupLayout(tabla);
        tabla.setLayout(tablaLayout);
        tablaLayout.setHorizontalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(tablaLayout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tablaLayout.setVerticalGroup(
            tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        add(tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    public void llenarTablaExistencia(){
        limpiarTabla();
        IServicioExistencia ptt = ServicioExistenciaFabrica.construir();
        var productos = ptt.obteerExistencia();
        Object[] datos = new Object[modelo.getColumnCount()];

        for (Existencia item : productos) {

            datos[0] = item.getAlmacen().getNombre();
            datos[1] = item.getAlmacen().gettAlmacen();
            datos[2] = item.getProducto().getCodProducto();
            datos[3] = item.getProducto().getNombre();
            datos[4] = item.getProducto().getDescripcion();
            datos[5] = item.getProducto().getCategoria().getNombre();
            datos[6] = item.getProducto().getpCompra();
            datos[7] = item.getProducto().getpVenta();
            datos[8] = item.getProducto().gettGuardado();
            datos[9] = item.getUbicacion();
            datos[10] = item.getCantidad();
            
            modelo.addRow(datos);
        }
        this.jTable1.setModel(modelo);
    }
    
    private void limpiarTabla() {
        for (int i = 0; i < this.jTable1.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel tabla;
    // End of variables declaration//GEN-END:variables
}
