/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;


import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;
import manejoProductos.transaccion.IServicioTransaccion;
import manejoProductos.transaccion.ServicioTransaccionFabrica;
import manejoProductos.transaccion.Transaccion;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Brayan
 */
public class VEstadistica extends javax.swing.JPanel {

    /**
     * Creates new form VEstadistica
     */

    /*private DefaultCategoryDataset datos;
    private ArrayList<Dato> lista;
    private ChartPanel panel;
    private JFreeChart graficoBarras;
    
    public VEstadistica() {
        initComponents();
       // lista = new ArrayList<>();
        datos = new DefaultCategoryDataset();
        cargarDatos();
        actualizarGraficos();
        System.out.println("estos somos todos");
    }
    
    public JPanel getJPnael(){
        return jPanel1;
    }
    
    public void setLista(ArrayList x){
        lista = x;
    }
    
    public ArrayList getLista(){
        return lista;
    }
    
    public void cargarDatos(){
        for(int i=0;i<lista.size();i++){
            datos.setValue(lista.get(i).getCantidad(), lista.get(i).getCategoria(), lista.get(i).getCategoria());
        }
    }
    
    public void actualizarGraficos(){
        graficoBarras = ChartFactory.createBarChart3D(
                "Cantidad de salidas de productos",
                "Categoria",
                "Cantidad",
                datos,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        panel = new ChartPanel(graficoBarras);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(725,291));
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel,BorderLayout.NORTH);
    }
    
    public void cargarCategoriaLista(int cantidad,String categoria){
        boolean existe = false;
        int pos = 0;
        for(int i=0;i<lista.size() && !existe;i++){
            if(lista.get(i).getCategoria().equals(categoria)){
                existe = true;
                pos = i;
            }
        }
        IServicioTransaccion e = ServicioTransaccionFabrica.construir();
        System.out.println("datos estadisticos");
        if(!existe){
            var resultado = e.obtener("Entrada");
            for(Transaccion item : resultado){
                //Dato p = new Dato(item.getCantidad(),item.getProdcuto().getCodProducto());
                //lista.add(p);
            }
            
        }else{
            lista.get(pos).setCantidad(lista.get(pos).getCantidad() + cantidad);
        }
    }*/
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
